################################################
#
#
#
#
#
################################################

FROM		alpine:3.2
MAINTAINER	Ehud Kaldor <ehud@unfairfunction.org>

RUN 		apk add musl && apk update && \
		rm -rf /var/cache/apk/*
